const Information = {
  LogoPackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Basic Logo Package",
          price: "35",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "3 Custom Logo Design Concepts",
            "1 Dedicated Designer",
            "1 Revisions",
            "2 hours TAT",
            "100% Unique Design Guarantee",
            "100% Satisfaction Guarantee",
            "100% Money Back Guarantee *",
            "100% Ownership Rights",
          ],
        },
      },
      type: "Logo",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Start Up Logo Package",
          price: "65",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "4 Custom Logo Design Concepts",
            "By 2 Designers",
            "Unlimited Revisions",
            "24 to 48 hours TAT",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee*",
            "100% Ownership Rights",
          ],
        },
      },
      type: "Logo",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Professional Logo Package",
          price: "99",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "Unlimited Logo Design Concepts",
            "By 4 Industry Based Designers",
            "UNLIMITED Revisions",
            "FREE MS Electronic Letterhead",
            "FREE Custom Stationery Design",
            "(Letterhead, Business Card, Envelope)",
            "24 to 48 hours TAT",
            "FREE File Formats (EPS, Ai, GIF, JPEG, PSD)",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee",
            "100% Ownership Rights",
          ],
        },
      },
      type: "Logo",
    },
    {
      data: {
        id: 4,
        Package: {
          Cat: "Elite Logo Package",
          price: "149",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "UNLIMITED Logo Design Concepts",
            "By 8 Award Winning Designers",
            "Free Icon Design",
            "FREE Custom Stationery Design",
            "(Letterhead, Business Card, Envelope, Invoice)",
            "Double Side Flyer (OR) Bi-Fold Brochure",
            "FREE MS Electronic Letterhead",
            "Email Signature Design",
            "UNLIMITED Revisions",
            "48 to 72 hours TAT",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee",
            "100% Ownership Rights",
          ],
        },
      },
      type: "Logo",
    },
    {
      data: {
        id: 5,
        Package: {
          Cat: "Gold Logo Package",
          price: "249",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "UNLIMITED Logo Design Concepts",
            "By 8 Award Winning Designers",
            "Icon Design",
            "UNLIMITED Revisions",
            "2 Stationary Design Sets (Business Card, Letterhead, Envelope)",
            "FREE MS Word Letterhead",
            "Free Email Signature",
            "3 Page Custom Website",
            "2 Stock Photos",
            "2 Banner Designs",
            "jQuery Slider",
            "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
          ],
        },
      },
      type: "Logo",
    },
  ],
  WebsitePackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Basic Website",
          price: "244",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "2 Stock Images",
            "3 Page Website",
            "1 jQuery Slider Banner",
            "Contact/Query Form",
            "Complete W3C CertifiedHTML",
            "48 to 72 hours TAT",
            "Complete Deployment",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
            "Mobile Responsive will be Additional $200*CMS will be Additional $250",
          ],
        },
      },
      type: "Website",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Startup Website Packages",
          price: "394",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "3 Banner Design",
            "1 jQuery Slider Banner",
            "FREE Google Friendly Sitemap",
            "Complete W3C Certified HTML",
            "48 to 72 hours TAT",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
            "Mobile Responsive will be Additional $200*",
            "CMS will be Additional $250*",
          ],
        },
      },
      type: "Website",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Professional Website Packages",
          price: "844",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "10 Unique Pages Website",
            "CMS / Admin Panel Support",
            "8 Stock images",
            "5 Banner Designs",
            "1 jQuery Slider Banner",
            "FREE Google Friendly Sitemap",
            "Complete W3C Certified HTML",
            "48 to 72 hours TAT",
            "Complete Deployment",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
            "Mobile Responsive will be Additional $200*",
          ],
        },
      },
      type: "Website",
    },
    {
      data: {
        id: 4,
        Package: {
          Cat: "Elite Website Packages",
          price: "1,494",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "Upto 15 Unique Pages Website",
            "Conceptual and Dynamic Website",
            "Mobile Responsive",
            "Online Reservation/Appointment Tool (Optional)",
            "Online Payment Integration (Optional)",
            "Custom Forms",
            "Lead Capturing Forms (Optional)",
            "Striking Hover Effects",
            "Newsletter Subscription (Optional)",
            "Newsfeed Integration",
            "Social Media Integration",
            "Search Engine Submission",
            "5 Stock Photos",
            "3 Unique Banner Design",
            "1 jQuery Slider Banner",
            "Complete W3C Certified HTML",
            "48 to 72 hours TAT",
            "Complete Deployment",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
          ],
        },
      },
      type: "Website",
    },
    {
      data: {
        id: 5,
        Package: {
          Cat: "Corporate Website Packages",
          price: "2,394",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "15 to 20 Pages Website",
            "Custom Made",
            "Interactive",
            "Dynamic & High End Design",
            "Custom WP (or) Custom PHP Development",
            "1 jQuery Slider Banner",
            "Up to 10 Custom Made Banner Designs",
            "10 Stock Images",
            "Unlimited Revisions",
            "Special Hoover Effects",
            "Content Management System (CMS)",
            "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
            "Online Payment Integration (Optional)",
            "Multi Lingual (Optional)",
            "Custom Dynamic Forms (Optional)",
            "Signup Area (For Newsletters",
            "Offers etc.)",
            "Search Bar",
            "Live Feeds of Social Networks integration (Optional)",
            "Mobile Responsive",
            "FREE 5 Years Domain Name",
            "Free Google Friendly Sitemap",
            "Search Engine Submission",
            "Complete W3C Certified HTML",
            "Industry Specified Team of Expert Designers and Developers",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
          ],
        },
      },
      type: "Website",
    },
    {
      data: {
        id: 6,
        Package: {
          Cat: "Business Website Packages",
          price: "2,999",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "15 Seconds 2D Explainer Video",
            "Voice - Over & Sound Effects",
            "Professional Script Writing",
            "Storyboard",
            "SEO Meta Tags",
            "15 to 20 Pages Website",
            "Custom Made",
            "Interactive",
            "Dynamic & High End Design",
            "Custom WP (or) Custom PHP Development",
            "1 jQuery Slider Banner",
            "Up to 10 Custom Made Banner Designs",
            "10 Stock Images",
            "Unlimited Revisions",
            "Special Hoover Effects",
            "Content Management System (CMS)",
            "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
            "Online Payment Integration (Optional)",
            "Multi Lingual (Optional)",
            "Custom Dynamic Forms (Optional)",
            "Signup Area (For Newsletters",
            "Offers etc.)",
            "Search Bar",
            "Live Feeds of Social Networks integration (Optional)",
            "Mobile Responsive",
            "FREE 5 Years Domain Name",
            "Free Google Friendly Sitemap",
            "Search Engine Submission",
            "Complete W3C Certified HTML",
            "Industry Specified Team of Expert Designers and Developers",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee *",
          ],
        },
      },
      type: "Website",
    },
  ],
  EcommercePackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Beginners E-Commerce Package",
          price: "789",
          list: [
            "Up-to 10 Unique Pages Website",
            "Up-to 100 Products",
            "Content Management System (CMS)",
            "Mobile Responsive",
            "Mini Shopping Cart Integration",
            "Payment Module Integration",
            "Free Google Friendly Sitemap",
            "Complete W3C Certified HTML",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee",
          ],
        },
      },
      type: "Ecommerce",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Beginners E-Commerce Package",
          price: "1,589",
          list: [
            "Up-to 15 Unique Pages Website",
            "Up-to 500 Products",
            "Conceptual and Dynamic Website",
            "Easy Product Search",
            "Product Reviews",
            "Content Management System (CMS)",
            "Mobile Responsive",
            "Full Shopping Cart Integration",
            "Payment Module Integration",
            "Sales & Inventory Management",
            "Jquery Slider",
            "Free Google Friendly Sitemap",
            "Custom Email Addresses",
            "Complete W3C Certified HTML",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee",
          ],
        },
      },
      type: "Ecommerce",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Beginners E-Commerce Package",
          price: "3,999",
          list: [
            "Unlimited Pages Website",
            "E-Commerce Store Design",
            "Product Detail Page Design",
            "Unlimited Products",
            "Unlimited Categories",
            "Product Rating & Reviews",
            "Unique Banner Slider",
            "Featured Products Showcase",
            "Full Shopping Cart Integration",
            "Multi-currency Support",
            "Online Payment Module Setup",
            "Facebook Shop Integration",
            "Sales & Inventory Management",
            "Easy Product Search",
            "Payment Gateway Integration",
            "Content Management System/CMS",
            "Customer Log-in Area",
            "Mobile Responsive",
            "Social Media Plugins Integration",
            "Tell a Friend Feature",
            "Social Media Pages",
            "Value Added Services",
            "FREE Custom Logo Design",
            "FREE Icon Design",
            "FREE Print Media",
            "FREE Stationary Design (Business Card",
            "Letterhead & Envelope Design)",
            "FREE Invoice Design",
            "FREE Bi-Fold Brochure (OR) 2-Sided Flyer Design",
            "FREE Product Catalog Design",
            "FREE Sign age Design (OR) Label Design",
            "FREE T-Shirt Design (OR) Car Wrap Design",
            "FREE Email Signature Design",
            "FREE Facebook",
            "Twitter",
            "YouTube",
            "Google+ & Pinterest Page Designs",
            "Dedicated Account Manager",
            "Unlimited Revisions",
            "All Final File Formats",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money Back Guarantee",
          ],
        },
      },
      type: "Ecommerce",
    },
  ],
  Smmpackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Startup",
          price: "250",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "3 Social Media Channels (Facebook / Twitter / Instagram)",
            "Social media account setup",
            "1 Post Design",
            "1 Cover Banner",
          ],
        },
      },
      type: "SMM",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Basic",
          price: "600",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "2 Social Media Channels (Facebook / Instagram)",
            "Social media account setup",
            "Complete Account Management",
            "3 Posts per week (per network)",
            "Custom Editorial calendar (Review before publishing)",
            "Dedicated account manager",
            "Dedicated Budget For Paid Advertising",
          ],
        },
      },
      type: "SMM",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Plus",
          price: "1200",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "4 Social Media Channels (Facebook / Twitter / Pinterest / Instagram)",
            "Social media account setup",
            "Complete Account Management 3 Posts per week (per network)",
            "Custom Editorial calendar (Review before publishing)",
            "Call to Action Integration",
            "End of Term Report",
            "Dedicated Account Manager",
            "Dedicated Budget For Paid Advertising",
          ],
        },
      },
      type: "SMM",
    },
  ],
  SEOPackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Basic SEO Package",
          price: "599",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "Prior Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "15 Selected Keywords Targeting",
            "Webpage Optimization",
            "15 Pages Keyword Targeted",
            "Meta Tags Creation",
            "Keyword Optimization",
            "Image Optimization",
            "Inclusion Of Anchors Tracking & Analysis",
            "Google Analytics Installation",
            "Google Webmaster Installation",
            "Call To Action Plan",
            "Creation Of Sitemaps Reporting",
            "Monthly Reporting",
            "Recommendation",
            "Email Supportn",
            "Phone Support Off Page Optimization",
            "Social Bookmarking",
            "Slide Share Marketing",
            "Forums/FAQâ€™s",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
          ],
        },
      },
      type: "SEO",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Start Up SEO Package",
          price: "999",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "Prior Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "30 Selected Keywords Targeting",
            "30 Pages Keywords Targeting",
            "Webpage Optimization",
            "Meta Tags Creation",
            "Image Optimization",
            "Inclusion Of Anchors Tracking & Analysis",
            "Google Analytics Installation",
            "Google Webmaster Installation",
            "Call To Action Plan",
            "Creation Of Sitemaps Reporting",
            "Monthly Reporting",
            "Recommendation",
            "Email Supportn",
            "Phone Support Off Page Optimization",
            "Social Bookmarking",
            "Slide Share Marketing",
            "Forums/FAQâ€™s",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
          ],
        },
      },
      type: "SEO",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Professional SEO Package",
          price: "1499",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "Prior Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "70 Selected Keywords Targeting",
            "50 Pages Keywords Targeting",
            "Webpage Optimization",
            "Meta Tags Creation",
            "Image Optimization",
            "Inclusion Of Anchors Indexing Modifications",
            "Tracking & Analysis",
            "Google Analytics Installation",
            "Google Webmaster Installation",
            "Call To Action Plan",
            "Creation Of Sitemaps",
            "Reporting",
            "Monthly Reporting",
            "Recommendation",
            "Email Support",
            "Phone Support Off Page Optimization",
            "Social Bookmarking",
            "Slide Share Marketing",
            "Forums/FAQâ€™s",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
            "Blog Content Creation",
            "Local SEO",
          ],
        },
      },
      type: "SEO",
    },
  ],
  BrandingPackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Basic Branding Package",
          price: "350",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "1 Stationery Design Set Concepts",
            "1 Flyer Design",
            "1 Banner Design Concept (any size)",
            "1 Brochure Design (Bi-fold/Tri-fold)",
            "2 Stock Photos",
            "T-Shirt Design (2 Concepts)",
            "Menu Card Design (2 Concepts)",
            "Free Social Media Banners (any 3)",
            "Free Email Signature",
            "Free Word Doc for Letterhead",
            "3 Revisions",
            "Turn Around 48-72 Hours",
            "Print Ready Formats",
          ],
        },
      },
      type: "Branding",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Start Up Branding Package",
          price: "500",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "2 Stationery Design Set Concepts",
            "2 Flyer Design",
            "2 Banner Design Concept (any size)",
            "2 Brochure Design concept (Bi-fold/Tri-fold)",
            "4 Stock Photos",
            "T-Shirt Design (3 Concepts)",
            "Menu Card Design (3 Concepts)",
            "Free Social Media Banners (any 5)",
            "Free Email Signature",
            "Free Word Doc for Letterhead",
            "4 Revisions",
            "Turn Around 48-72 Hours",
            "Print Ready Formats",
          ],
        },
      },
      type: "Branding",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Professional Branding Package",
          price: "650",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "4 Stationery Design Set Concepts",
            "3 Flyer Design",
            "3 Banner Design Concept (any size)",
            "4 Brochure Design concept (Bi-fold/Tri-fold)",
            "5 Stock Photos",
            "T-Shirt Design (4 Concepts)",
            "Menu Card Design (4 Concepts)",
            "Free Social Media Banners (any 5)",
            "Free Email Signature",
            "Free Word Doc for Letterhead",
            "Unlimited Revisions",
            "Turn Around 48-72 Hours",
            "Print Ready Formats",
          ],
        },
      },
      type: "Branding",
    },
  ],
  AnimationPackages: [
    {
      data: {
        id: 1,
        Package: {
          Cat: "Basic Animation Package",
          price: "999",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "30 Sec. Duration",
            "Script Creation",
            "Storyboard Conceptualization",
            "Storyboard Designing",
            "Voice-over",
            "Animation & Sound Effect",
          ],
        },
      },
      type: "Animation",
    },
    {
      data: {
        id: 2,
        Package: {
          Cat: "Start Up Animation Package",
          price: "1899",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "60 Sec. Duration",
            "Script Creation",
            "Storyboard Conceptualization",
            "Characters Modelling",
            "Voice-over",
            "Animation & Sound Effect",
          ],
        },
      },
      type: "Animation",
    },
    {
      data: {
        id: 3,
        Package: {
          Cat: "Professional Animation Package",
          price: "2499",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "90 Sec. Duration",
            "Script Creation",
            "Storyboard Conceptualization",
            "Voice-over",
            "Animation & Sound Effect",
          ],
        },
      },
      type: "Animation",
    },
    {
      data: {
        id: 4,
        Package: {
          Cat: "Professional Animation Package",
          price: "3199",
          description:
            "Suitable for potential super-startups and brand revamps for companies.",
          list: [
            "120 Sec. Duration",
            "Script Creation",
            "Storyboard Conceptualization",
            "Voice-over",
            "Animation & Sound Effect",
          ],
        },
      },
      type: "Animation",
    },
  ],
};

export default Information;
